[package]
name = "file_integrity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.2"
hex = "0.4.3"
clap = { version = "3.1.12", features = ["derive"] }
